Repository y-crdt/pycrdt-websocket, pull requests merged in 2024-10, with the labels that each got.

#72 Update GitHub actions
  .github/workflows/test.yml
Labels: maintenance

#74 Remove the awareness in favor of the one from pycrdt
  pycrdt_websocket/awareness.py
  pyproject.toml
Labels: maintenance

#73 Broadcast server awareness to all clients
  pycrdt_websocket/yroom.py
  pyproject.toml
Labels: enhancement

#76 Apply awareness updates to server awareness
  pycrdt_websocket/yroom.py
Labels: bug

#78 Start the server awareness
  pycrdt_websocket/yroom.py
  pyproject.toml
Labels: enhancement
