Repository y-crdt/pycrdt-websocket, pull requests merged in 2024-12, with the labels that each got.

#89 Dead code
  pycrdt_websocket/websocket_provider.py
Labels: maintenance

#91 Update client documentation
  docs/usage/client.md
Labels: documentation

#94 Remove client on failure
  pycrdt_websocket/yroom.py
Labels: bug

#95 Update client/server examples
  docs/usage/client.md
  docs/usage/server.md
  pycrdt_websocket/websocket.py
Labels: documentation
